### ISSUE TITLE
Executables inside repo - equals a huge repo

### ISSUE THREAD

**Issue by uffejakobsen** [fieserWolF/convertron3000#2]
Hi,

(same problem at ditheridoo project)

Having executables inside the repo seems like a really bad idea

Because of this - the repo is already over to 70MB when cloning - for a rather small/simple project

    and I will guess that it will keep growing in this manner - if this approach continues

Why not use other means of keeping the releases outside the repo ? :-)

**Comment by fieserWolF** [comment]
I removed the standalone executables from the repository. They can now be found at "Releases":
https://github.com/fieserWolF/convertron3000/releases
